# 你的名字
name: 你的名字

# 博客描述
description: 博客描述

description-c: 不忘初心，一生浪漫 # 好词好句

# 你的LOGO（头像，推荐100x100（必须10x10到200x200之内）），这里用这个项目logo.(大陆也能访问)
avatar: https://bg-r.github.io/images/BGlogo.png

#
# Flags below are optional
#

# 这是联系方式，必填。
github: # GitHub 用户名 必填
qq: 1218374083  # QQ号 必填


url:
baseurl: # 地址，如rocky-co.github.io或rocky.net...



permalink: /:title/

version: v1.2.0


kramdown:
  input: GFM
  # 语法高亮
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded 


gems:
  - jekyll-sitemap 
  - jekyll-feed 


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
